apiVersion: promoter.argoproj.io/v1alpha1
kind: ControllerConfiguration
metadata:
  name: {{ include "gitops-promoter.fullname" . }}-controller-configuration
  labels:
    app.kubernetes.io/part-of: promoter
  {{- include "gitops-promoter.labels" . | nindent 4 }}
spec:
  argocdCommitStatusRequeueDuration: 5m
  changeTransferPolicyRequeueDuration: 5m
  promotionStrategyRequeueDuration: 5m
  pullRequest:
    template:
      description: This PR is promoting the environment branch `{{ .ChangeTransferPolicy.Spec.ActiveBranch
        }}` which is currently on dry sha {{ .ChangeTransferPolicy.Status.Active.Dry.Sha
        }} to dry sha {{ .ChangeTransferPolicy.Status.Proposed.Dry.Sha }}.
      title: Promote {{ trunc 5 .ChangeTransferPolicy.Status.Proposed.Dry.Sha }} to
        `{{ .ChangeTransferPolicy.Spec.ActiveBranch }}`
  pullRequestRequeueDuration: 5m
