apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gitops-promoter.fullname" . }}-manager-role
  labels:
  {{- include "gitops-promoter.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - promoter.argoproj.io
  resources:
  - argocdcommitstatuses
  - changetransferpolicies
  - clusterscmproviders
  - commitstatuses
  - controllerconfigurations
  - gitrepositories
  - promotionstrategies
  - pullrequests
  - revertcommits
  - scmproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - promoter.argoproj.io
  resources:
  - argocdcommitstatuses/finalizers
  - changetransferpolicies/finalizers
  - clusterscmproviders/finalizers
  - commitstatuses/finalizers
  - controllerconfigurations/finalizers
  - gitrepositories/finalizers
  - promotionstrategies/finalizers
  - pullrequests/finalizers
  - revertcommits/finalizers
  - scmproviders/finalizers
  verbs:
  - update
- apiGroups:
  - promoter.argoproj.io
  resources:
  - argocdcommitstatuses/status
  - changetransferpolicies/status
  - clusterscmproviders/status
  - commitstatuses/status
  - controllerconfigurations/status
  - gitrepositories/status
  - promotionstrategies/status
  - pullrequests/status
  - revertcommits/status
  - scmproviders/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gitops-promoter.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: promoter
    app.kubernetes.io/part-of: promoter
  {{- include "gitops-promoter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "gitops-promoter.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "gitops-promoter.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
